tasks:
  - name: Backend Console
    init: go get
    command: go run .
  - name: Frontend Console
    init: cd frontend && npm install
    command: REACT_APP_API_URL=`gp url 8080` npm start

ports:
  - name: Frontend
    port: 3000
    onOpen: open-browser
  - name: Backend
    port: 8080
    onOpen: open-browser
    visibility: public
