tasks:
  - name: Backend Console
    init: go get
    command: go run .
  - name: Frontend Console
    init: cd frontend && npm install
    command: REACT_APP_API_URL=`gp url 8080` npm start

ports:
    # Note both ports have visiblity public i.e. anyone with the Gitpod URL
    # could access them. This is because with private ports CORS prevents the
    # GUI from interacting with the API. See:
    # https://github.com/cleodora-forecasting/cleodora/issues/27
  - name: Frontend
    description: React frontend to interact with the GraphQL API
    port: 3000
    onOpen: open-browser
    visibility: public
  - name: Backend
    description: GraphQL API
    port: 8080
    onOpen: open-browser
    visibility: public
