tasks:
  - name: Backend Console
    init: ./installDependencies.sh
    command: |
        gp sync-done install-dependencies
        printf "\n\n"
        echo "# Execute the following command to start the backend:"
        echo 'go run .'

  - name: Frontend Console
    init: gp sync-await install-dependencies
    command: |
        cd frontend
        printf "\n\n"
        echo "# Execute the following command to start the frontend:"
        echo 'REACT_APP_API_URL=`gp url 8080` npm start'

  - name: Website Console
    init: gp sync-await install-dependencies
    command: |
        cd website
        printf "\n\n"
        echo "# Execute the following command to start the website:"
        echo 'hugo server'

ports:
    # Note both ports have visiblity public i.e. anyone with the Gitpod URL
    # could access them. This is because with private ports CORS prevents the
    # GUI from interacting with the API. See:
    # https://github.com/cleodora-forecasting/cleodora/issues/27
  - name: Frontend
    description: React frontend to interact with the GraphQL API
    port: 3000
    onOpen: open-browser
    visibility: public
  - name: Backend
    description: GraphQL API
    port: 8080
    onOpen: open-browser
    visibility: public
