tasks:
  - name: Console
    init: |
        ./scripts/installDependencies.sh
        brew install hugo # Will install the extended flavor
    command: |
        echo "Check the 'Development Documentation' for help:"
        echo
        echo "https://github.com/cleodora-forecasting/cleodora/tree/main/dev_docs"
        echo

ports:
  - name: Website
    description: Instance of cleodora.org website
    port: 1313
    visibility: private

    # Note both ports below have visiblity public i.e. anyone with the Gitpod
    # URL could access them. This is because with private ports CORS prevents
    # the GUI from interacting with the API. See:
    # https://github.com/cleodora-forecasting/cleodora/issues/27

  - name: Frontend
    description: React frontend to interact with the GraphQL API
    port: 3000
    visibility: public

  - name: Backend
    description: GraphQL API
    port: 8080
    visibility: public
