run:
  skip-dirs:
    - bin
    - build
    - design
    - docs
    - e2e_tests
    - frontend
    - website

linters:
  disable-all: true
  enable:
    - errcheck
    - gci
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
  disable:

linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/cleodora-forecasting/cleodora)
