# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    - rm -rf frontend/build
    - sh -c 'cd frontend; npm run build'
    - rm -rf cleosrv/cleosrv/frontend_build
    - cp -r frontend/build cleosrv/cleosrv/frontend_build
builds:
  - id: cleosrv
    binary: cleosrv
    main: ./cleosrv
    ldflags:
      - -X github.com/cleodora-forecasting/cleodora/cleoutils.Version={{.Version}}
      - -X github.com/cleodora-forecasting/cleodora/cleoutils.VersionCommit={{.ShortCommit}}
      - -X github.com/cleodora-forecasting/cleodora/cleoutils.VersionDate={{.CommitDate}}
    flags:
      - -tags=production
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: darwin
        goarch: arm64
      - goos: windows
        goarch: arm64

  - id: cleoc
    binary: cleoc
    main: ./cleoc
    ldflags:
      - -X github.com/cleodora-forecasting/cleodora/cleoutils.Version={{.Version}}
      - -X github.com/cleodora-forecasting/cleodora/cleoutils.VersionCommit={{.ShortCommit}}
      - -X github.com/cleodora-forecasting/cleodora/cleoutils.VersionDate={{.CommitDate}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: darwin
        goarch: arm64
      - goos: windows
        goarch: arm64
dockers:
  - image_templates:
      - cleodora/cleodora
    ids:
      - cleosrv
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: '{{ incminor .Version }}-dev+{{ replace .CommitDate ":" "" }}.{{ .ShortCommit }}'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

# modelines, feel free to remove those if you don't want/use them:
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
