# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    - rm -rf frontend/build
    - sh -c 'cd frontend; npm run build'
    - rm -rf cleosrv/cleosrv/frontend_build
    - cp -r frontend/build cleosrv/cleosrv/frontend_build
builds:
  - id: cleosrv
    binary: cleosrv
    main: ./cleosrv
    ldflags:
      - -X github.com/cleodora-forecasting/cleodora/cleoutils.Version={{.Version}}
      - -X github.com/cleodora-forecasting/cleodora/cleoutils.VersionCommit={{.ShortCommit}}
      - -X github.com/cleodora-forecasting/cleodora/cleoutils.VersionDate={{.CommitDate}}
      - -extldflags=-static
    flags:
      - -tags=production
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: darwin
        goarch: arm64
      - goos: windows
        goarch: arm64

  - id: cleoc
    binary: cleoc
    main: ./cleoc/cmd
    ldflags:
      - -X github.com/cleodora-forecasting/cleodora/cleoutils.Version={{.Version}}
      - -X github.com/cleodora-forecasting/cleodora/cleoutils.VersionCommit={{.ShortCommit}}
      - -X github.com/cleodora-forecasting/cleodora/cleoutils.VersionDate={{.CommitDate}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: darwin
        goarch: arm64
      - goos: windows
        goarch: arm64
dockers:
  - image_templates:
      - "cleodora/cleodora:{{ .Tag }}"
      - "cleodora/cleodora:v{{ .Major }}"
      - "cleodora/cleodora:v{{ .Major }}.{{ .Minor }}"
      - "cleodora/cleodora:latest"
    ids:
      - cleosrv
    extra_files:
      - cleosrv.example.yml

archives:
  - id: cleosrv
    builds:
      - cleosrv
    name_template: 'cleosrv_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}{{ with .Mips }}_{{ . }}{{ end }}{{ if not (eq .Amd64 "v1") }}{{ .Amd64 }}{{ end }}'
    format_overrides:
      - goos: windows
        format: zip
    files:
      - none*
  - id: cleoc
    builds:
      - cleoc
    name_template: 'cleoc_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}{{ with .Mips }}_{{ . }}{{ end }}{{ if not (eq .Amd64 "v1") }}{{ .Amd64 }}{{ end }}'
    format_overrides:
      - goos: windows
        format: zip
    files:
      - none*

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: '{{ incminor .Version }}-dev+{{ replace .CommitDate ":" "" }}.{{ .ShortCommit }}'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

# modelines, feel free to remove those if you don't want/use them:
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
