// Code generated by ent, DO NOT EDIT.

package outcome

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/cleodora-forecasting/cleodora/cleosrv/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Outcome {
	return predicate.Outcome(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Outcome {
	return predicate.Outcome(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Outcome {
	return predicate.Outcome(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Outcome {
	return predicate.Outcome(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Outcome {
	return predicate.Outcome(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Outcome {
	return predicate.Outcome(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Outcome {
	return predicate.Outcome(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Outcome {
	return predicate.Outcome(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Outcome {
	return predicate.Outcome(sql.FieldLTE(FieldID, id))
}

// Text applies equality check predicate on the "text" field. It's identical to TextEQ.
func Text(v string) predicate.Outcome {
	return predicate.Outcome(sql.FieldEQ(FieldText, v))
}

// Correct applies equality check predicate on the "correct" field. It's identical to CorrectEQ.
func Correct(v bool) predicate.Outcome {
	return predicate.Outcome(sql.FieldEQ(FieldCorrect, v))
}

// TextEQ applies the EQ predicate on the "text" field.
func TextEQ(v string) predicate.Outcome {
	return predicate.Outcome(sql.FieldEQ(FieldText, v))
}

// TextNEQ applies the NEQ predicate on the "text" field.
func TextNEQ(v string) predicate.Outcome {
	return predicate.Outcome(sql.FieldNEQ(FieldText, v))
}

// TextIn applies the In predicate on the "text" field.
func TextIn(vs ...string) predicate.Outcome {
	return predicate.Outcome(sql.FieldIn(FieldText, vs...))
}

// TextNotIn applies the NotIn predicate on the "text" field.
func TextNotIn(vs ...string) predicate.Outcome {
	return predicate.Outcome(sql.FieldNotIn(FieldText, vs...))
}

// TextGT applies the GT predicate on the "text" field.
func TextGT(v string) predicate.Outcome {
	return predicate.Outcome(sql.FieldGT(FieldText, v))
}

// TextGTE applies the GTE predicate on the "text" field.
func TextGTE(v string) predicate.Outcome {
	return predicate.Outcome(sql.FieldGTE(FieldText, v))
}

// TextLT applies the LT predicate on the "text" field.
func TextLT(v string) predicate.Outcome {
	return predicate.Outcome(sql.FieldLT(FieldText, v))
}

// TextLTE applies the LTE predicate on the "text" field.
func TextLTE(v string) predicate.Outcome {
	return predicate.Outcome(sql.FieldLTE(FieldText, v))
}

// TextContains applies the Contains predicate on the "text" field.
func TextContains(v string) predicate.Outcome {
	return predicate.Outcome(sql.FieldContains(FieldText, v))
}

// TextHasPrefix applies the HasPrefix predicate on the "text" field.
func TextHasPrefix(v string) predicate.Outcome {
	return predicate.Outcome(sql.FieldHasPrefix(FieldText, v))
}

// TextHasSuffix applies the HasSuffix predicate on the "text" field.
func TextHasSuffix(v string) predicate.Outcome {
	return predicate.Outcome(sql.FieldHasSuffix(FieldText, v))
}

// TextEqualFold applies the EqualFold predicate on the "text" field.
func TextEqualFold(v string) predicate.Outcome {
	return predicate.Outcome(sql.FieldEqualFold(FieldText, v))
}

// TextContainsFold applies the ContainsFold predicate on the "text" field.
func TextContainsFold(v string) predicate.Outcome {
	return predicate.Outcome(sql.FieldContainsFold(FieldText, v))
}

// CorrectEQ applies the EQ predicate on the "correct" field.
func CorrectEQ(v bool) predicate.Outcome {
	return predicate.Outcome(sql.FieldEQ(FieldCorrect, v))
}

// CorrectNEQ applies the NEQ predicate on the "correct" field.
func CorrectNEQ(v bool) predicate.Outcome {
	return predicate.Outcome(sql.FieldNEQ(FieldCorrect, v))
}

// HasProbabilities applies the HasEdge predicate on the "probabilities" edge.
func HasProbabilities() predicate.Outcome {
	return predicate.Outcome(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ProbabilitiesTable, ProbabilitiesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasProbabilitiesWith applies the HasEdge predicate on the "probabilities" edge with a given conditions (other predicates).
func HasProbabilitiesWith(preds ...predicate.Probability) predicate.Outcome {
	return predicate.Outcome(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(ProbabilitiesInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ProbabilitiesTable, ProbabilitiesColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Outcome) predicate.Outcome {
	return predicate.Outcome(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Outcome) predicate.Outcome {
	return predicate.Outcome(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Outcome) predicate.Outcome {
	return predicate.Outcome(func(s *sql.Selector) {
		p(s.Not())
	})
}
