// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

// Information about the application itself e.g. the current version.
type Metadata struct {
	Version string `json:"version"`
}
