baseURL = 'https://cleodora.org/'
languageCode = 'en-us'
title = 'Cleodora Forecasting'

[module]
[[module.imports]]
path = 'github.com/alex-shpak/hugo-book'

[params]
  BookLogo = 'logo.png'
  images = ['/logo_full.png']

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]
[[menu.after]]
  name = "GitHub"
  url = "https://github.com/cleodora-forecasting/cleodora"
  weight = 10
