baseURL = 'https://cleodora.org/'
languageCode = 'en-us'
title = 'Cleodora Forecasting'

enableGitInfo = true

[module]
[[module.imports]]
path = 'github.com/alex-shpak/hugo-book'

[params]
  BookLogo = 'logo.png'
  images = ['/logo_full.png']
  BookRepo = 'https://github.com/cleodora-forecasting/cleodora'
  BookEditPath = 'edit/main/website'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]
[[menu.after]]
  name = "GitHub"
  url = "https://github.com/cleodora-forecasting/cleodora"
  weight = 10
