// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/cleodora-forecasting/cleodora/cleosrv/ent/estimate"
	"github.com/cleodora-forecasting/cleodora/cleosrv/ent/forecast"
	"github.com/cleodora-forecasting/cleodora/cleosrv/ent/predicate"
)

// ForecastQuery is the builder for querying Forecast entities.
type ForecastQuery struct {
	config
	ctx                *QueryContext
	order              []OrderFunc
	inters             []Interceptor
	predicates         []predicate.Forecast
	withEstimates      *EstimateQuery
	modifiers          []func(*sql.Selector)
	loadTotal          []func(context.Context, []*Forecast) error
	withNamedEstimates map[string]*EstimateQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ForecastQuery builder.
func (fq *ForecastQuery) Where(ps ...predicate.Forecast) *ForecastQuery {
	fq.predicates = append(fq.predicates, ps...)
	return fq
}

// Limit the number of records to be returned by this query.
func (fq *ForecastQuery) Limit(limit int) *ForecastQuery {
	fq.ctx.Limit = &limit
	return fq
}

// Offset to start from.
func (fq *ForecastQuery) Offset(offset int) *ForecastQuery {
	fq.ctx.Offset = &offset
	return fq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (fq *ForecastQuery) Unique(unique bool) *ForecastQuery {
	fq.ctx.Unique = &unique
	return fq
}

// Order specifies how the records should be ordered.
func (fq *ForecastQuery) Order(o ...OrderFunc) *ForecastQuery {
	fq.order = append(fq.order, o...)
	return fq
}

// QueryEstimates chains the current query on the "estimates" edge.
func (fq *ForecastQuery) QueryEstimates() *EstimateQuery {
	query := (&EstimateClient{config: fq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := fq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := fq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(forecast.Table, forecast.FieldID, selector),
			sqlgraph.To(estimate.Table, estimate.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, forecast.EstimatesTable, forecast.EstimatesColumn),
		)
		fromU = sqlgraph.SetNeighbors(fq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Forecast entity from the query.
// Returns a *NotFoundError when no Forecast was found.
func (fq *ForecastQuery) First(ctx context.Context) (*Forecast, error) {
	nodes, err := fq.Limit(1).All(setContextOp(ctx, fq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{forecast.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (fq *ForecastQuery) FirstX(ctx context.Context) *Forecast {
	node, err := fq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Forecast ID from the query.
// Returns a *NotFoundError when no Forecast ID was found.
func (fq *ForecastQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = fq.Limit(1).IDs(setContextOp(ctx, fq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{forecast.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (fq *ForecastQuery) FirstIDX(ctx context.Context) int {
	id, err := fq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Forecast entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Forecast entity is found.
// Returns a *NotFoundError when no Forecast entities are found.
func (fq *ForecastQuery) Only(ctx context.Context) (*Forecast, error) {
	nodes, err := fq.Limit(2).All(setContextOp(ctx, fq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{forecast.Label}
	default:
		return nil, &NotSingularError{forecast.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (fq *ForecastQuery) OnlyX(ctx context.Context) *Forecast {
	node, err := fq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Forecast ID in the query.
// Returns a *NotSingularError when more than one Forecast ID is found.
// Returns a *NotFoundError when no entities are found.
func (fq *ForecastQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = fq.Limit(2).IDs(setContextOp(ctx, fq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{forecast.Label}
	default:
		err = &NotSingularError{forecast.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (fq *ForecastQuery) OnlyIDX(ctx context.Context) int {
	id, err := fq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Forecasts.
func (fq *ForecastQuery) All(ctx context.Context) ([]*Forecast, error) {
	ctx = setContextOp(ctx, fq.ctx, "All")
	if err := fq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Forecast, *ForecastQuery]()
	return withInterceptors[[]*Forecast](ctx, fq, qr, fq.inters)
}

// AllX is like All, but panics if an error occurs.
func (fq *ForecastQuery) AllX(ctx context.Context) []*Forecast {
	nodes, err := fq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Forecast IDs.
func (fq *ForecastQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	ctx = setContextOp(ctx, fq.ctx, "IDs")
	if err := fq.Select(forecast.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (fq *ForecastQuery) IDsX(ctx context.Context) []int {
	ids, err := fq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (fq *ForecastQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, fq.ctx, "Count")
	if err := fq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, fq, querierCount[*ForecastQuery](), fq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (fq *ForecastQuery) CountX(ctx context.Context) int {
	count, err := fq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (fq *ForecastQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, fq.ctx, "Exist")
	switch _, err := fq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (fq *ForecastQuery) ExistX(ctx context.Context) bool {
	exist, err := fq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ForecastQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (fq *ForecastQuery) Clone() *ForecastQuery {
	if fq == nil {
		return nil
	}
	return &ForecastQuery{
		config:        fq.config,
		ctx:           fq.ctx.Clone(),
		order:         append([]OrderFunc{}, fq.order...),
		inters:        append([]Interceptor{}, fq.inters...),
		predicates:    append([]predicate.Forecast{}, fq.predicates...),
		withEstimates: fq.withEstimates.Clone(),
		// clone intermediate query.
		sql:  fq.sql.Clone(),
		path: fq.path,
	}
}

// WithEstimates tells the query-builder to eager-load the nodes that are connected to
// the "estimates" edge. The optional arguments are used to configure the query builder of the edge.
func (fq *ForecastQuery) WithEstimates(opts ...func(*EstimateQuery)) *ForecastQuery {
	query := (&EstimateClient{config: fq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	fq.withEstimates = query
	return fq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Title string `json:"title,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Forecast.Query().
//		GroupBy(forecast.FieldTitle).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (fq *ForecastQuery) GroupBy(field string, fields ...string) *ForecastGroupBy {
	fq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ForecastGroupBy{build: fq}
	grbuild.flds = &fq.ctx.Fields
	grbuild.label = forecast.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Title string `json:"title,omitempty"`
//	}
//
//	client.Forecast.Query().
//		Select(forecast.FieldTitle).
//		Scan(ctx, &v)
func (fq *ForecastQuery) Select(fields ...string) *ForecastSelect {
	fq.ctx.Fields = append(fq.ctx.Fields, fields...)
	sbuild := &ForecastSelect{ForecastQuery: fq}
	sbuild.label = forecast.Label
	sbuild.flds, sbuild.scan = &fq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ForecastSelect configured with the given aggregations.
func (fq *ForecastQuery) Aggregate(fns ...AggregateFunc) *ForecastSelect {
	return fq.Select().Aggregate(fns...)
}

func (fq *ForecastQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range fq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, fq); err != nil {
				return err
			}
		}
	}
	for _, f := range fq.ctx.Fields {
		if !forecast.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if fq.path != nil {
		prev, err := fq.path(ctx)
		if err != nil {
			return err
		}
		fq.sql = prev
	}
	return nil
}

func (fq *ForecastQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Forecast, error) {
	var (
		nodes       = []*Forecast{}
		_spec       = fq.querySpec()
		loadedTypes = [1]bool{
			fq.withEstimates != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Forecast).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Forecast{config: fq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(fq.modifiers) > 0 {
		_spec.Modifiers = fq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, fq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := fq.withEstimates; query != nil {
		if err := fq.loadEstimates(ctx, query, nodes,
			func(n *Forecast) { n.Edges.Estimates = []*Estimate{} },
			func(n *Forecast, e *Estimate) { n.Edges.Estimates = append(n.Edges.Estimates, e) }); err != nil {
			return nil, err
		}
	}
	for name, query := range fq.withNamedEstimates {
		if err := fq.loadEstimates(ctx, query, nodes,
			func(n *Forecast) { n.appendNamedEstimates(name) },
			func(n *Forecast, e *Estimate) { n.appendNamedEstimates(name, e) }); err != nil {
			return nil, err
		}
	}
	for i := range fq.loadTotal {
		if err := fq.loadTotal[i](ctx, nodes); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (fq *ForecastQuery) loadEstimates(ctx context.Context, query *EstimateQuery, nodes []*Forecast, init func(*Forecast), assign func(*Forecast, *Estimate)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Forecast)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.Estimate(func(s *sql.Selector) {
		s.Where(sql.InValues(forecast.EstimatesColumn, fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.forecast_estimates
		if fk == nil {
			return fmt.Errorf(`foreign-key "forecast_estimates" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "forecast_estimates" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (fq *ForecastQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := fq.querySpec()
	if len(fq.modifiers) > 0 {
		_spec.Modifiers = fq.modifiers
	}
	_spec.Node.Columns = fq.ctx.Fields
	if len(fq.ctx.Fields) > 0 {
		_spec.Unique = fq.ctx.Unique != nil && *fq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, fq.driver, _spec)
}

func (fq *ForecastQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   forecast.Table,
			Columns: forecast.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: forecast.FieldID,
			},
		},
		From:   fq.sql,
		Unique: true,
	}
	if unique := fq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := fq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, forecast.FieldID)
		for i := range fields {
			if fields[i] != forecast.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := fq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := fq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := fq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := fq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (fq *ForecastQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(fq.driver.Dialect())
	t1 := builder.Table(forecast.Table)
	columns := fq.ctx.Fields
	if len(columns) == 0 {
		columns = forecast.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if fq.sql != nil {
		selector = fq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if fq.ctx.Unique != nil && *fq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range fq.predicates {
		p(selector)
	}
	for _, p := range fq.order {
		p(selector)
	}
	if offset := fq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := fq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// WithNamedEstimates tells the query-builder to eager-load the nodes that are connected to the "estimates"
// edge with the given name. The optional arguments are used to configure the query builder of the edge.
func (fq *ForecastQuery) WithNamedEstimates(name string, opts ...func(*EstimateQuery)) *ForecastQuery {
	query := (&EstimateClient{config: fq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	if fq.withNamedEstimates == nil {
		fq.withNamedEstimates = make(map[string]*EstimateQuery)
	}
	fq.withNamedEstimates[name] = query
	return fq
}

// ForecastGroupBy is the group-by builder for Forecast entities.
type ForecastGroupBy struct {
	selector
	build *ForecastQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (fgb *ForecastGroupBy) Aggregate(fns ...AggregateFunc) *ForecastGroupBy {
	fgb.fns = append(fgb.fns, fns...)
	return fgb
}

// Scan applies the selector query and scans the result into the given value.
func (fgb *ForecastGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, fgb.build.ctx, "GroupBy")
	if err := fgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ForecastQuery, *ForecastGroupBy](ctx, fgb.build, fgb, fgb.build.inters, v)
}

func (fgb *ForecastGroupBy) sqlScan(ctx context.Context, root *ForecastQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(fgb.fns))
	for _, fn := range fgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*fgb.flds)+len(fgb.fns))
		for _, f := range *fgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*fgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := fgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ForecastSelect is the builder for selecting fields of Forecast entities.
type ForecastSelect struct {
	*ForecastQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (fs *ForecastSelect) Aggregate(fns ...AggregateFunc) *ForecastSelect {
	fs.fns = append(fs.fns, fns...)
	return fs
}

// Scan applies the selector query and scans the result into the given value.
func (fs *ForecastSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, fs.ctx, "Select")
	if err := fs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ForecastQuery, *ForecastSelect](ctx, fs.ForecastQuery, fs, fs.inters, v)
}

func (fs *ForecastSelect) sqlScan(ctx context.Context, root *ForecastQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(fs.fns))
	for _, fn := range fs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*fs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := fs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
