// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/cleodora-forecasting/cleodora/cleosrv/ent/outcome"
	"github.com/cleodora-forecasting/cleodora/cleosrv/ent/predicate"
	"github.com/cleodora-forecasting/cleodora/cleosrv/ent/probability"
)

// OutcomeQuery is the builder for querying Outcome entities.
type OutcomeQuery struct {
	config
	ctx                    *QueryContext
	order                  []OrderFunc
	inters                 []Interceptor
	predicates             []predicate.Outcome
	withProbabilities      *ProbabilityQuery
	modifiers              []func(*sql.Selector)
	loadTotal              []func(context.Context, []*Outcome) error
	withNamedProbabilities map[string]*ProbabilityQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the OutcomeQuery builder.
func (oq *OutcomeQuery) Where(ps ...predicate.Outcome) *OutcomeQuery {
	oq.predicates = append(oq.predicates, ps...)
	return oq
}

// Limit the number of records to be returned by this query.
func (oq *OutcomeQuery) Limit(limit int) *OutcomeQuery {
	oq.ctx.Limit = &limit
	return oq
}

// Offset to start from.
func (oq *OutcomeQuery) Offset(offset int) *OutcomeQuery {
	oq.ctx.Offset = &offset
	return oq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (oq *OutcomeQuery) Unique(unique bool) *OutcomeQuery {
	oq.ctx.Unique = &unique
	return oq
}

// Order specifies how the records should be ordered.
func (oq *OutcomeQuery) Order(o ...OrderFunc) *OutcomeQuery {
	oq.order = append(oq.order, o...)
	return oq
}

// QueryProbabilities chains the current query on the "probabilities" edge.
func (oq *OutcomeQuery) QueryProbabilities() *ProbabilityQuery {
	query := (&ProbabilityClient{config: oq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := oq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := oq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(outcome.Table, outcome.FieldID, selector),
			sqlgraph.To(probability.Table, probability.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, outcome.ProbabilitiesTable, outcome.ProbabilitiesColumn),
		)
		fromU = sqlgraph.SetNeighbors(oq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Outcome entity from the query.
// Returns a *NotFoundError when no Outcome was found.
func (oq *OutcomeQuery) First(ctx context.Context) (*Outcome, error) {
	nodes, err := oq.Limit(1).All(setContextOp(ctx, oq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{outcome.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (oq *OutcomeQuery) FirstX(ctx context.Context) *Outcome {
	node, err := oq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Outcome ID from the query.
// Returns a *NotFoundError when no Outcome ID was found.
func (oq *OutcomeQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = oq.Limit(1).IDs(setContextOp(ctx, oq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{outcome.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (oq *OutcomeQuery) FirstIDX(ctx context.Context) int {
	id, err := oq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Outcome entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Outcome entity is found.
// Returns a *NotFoundError when no Outcome entities are found.
func (oq *OutcomeQuery) Only(ctx context.Context) (*Outcome, error) {
	nodes, err := oq.Limit(2).All(setContextOp(ctx, oq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{outcome.Label}
	default:
		return nil, &NotSingularError{outcome.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (oq *OutcomeQuery) OnlyX(ctx context.Context) *Outcome {
	node, err := oq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Outcome ID in the query.
// Returns a *NotSingularError when more than one Outcome ID is found.
// Returns a *NotFoundError when no entities are found.
func (oq *OutcomeQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = oq.Limit(2).IDs(setContextOp(ctx, oq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{outcome.Label}
	default:
		err = &NotSingularError{outcome.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (oq *OutcomeQuery) OnlyIDX(ctx context.Context) int {
	id, err := oq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Outcomes.
func (oq *OutcomeQuery) All(ctx context.Context) ([]*Outcome, error) {
	ctx = setContextOp(ctx, oq.ctx, "All")
	if err := oq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Outcome, *OutcomeQuery]()
	return withInterceptors[[]*Outcome](ctx, oq, qr, oq.inters)
}

// AllX is like All, but panics if an error occurs.
func (oq *OutcomeQuery) AllX(ctx context.Context) []*Outcome {
	nodes, err := oq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Outcome IDs.
func (oq *OutcomeQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	ctx = setContextOp(ctx, oq.ctx, "IDs")
	if err := oq.Select(outcome.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (oq *OutcomeQuery) IDsX(ctx context.Context) []int {
	ids, err := oq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (oq *OutcomeQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, oq.ctx, "Count")
	if err := oq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, oq, querierCount[*OutcomeQuery](), oq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (oq *OutcomeQuery) CountX(ctx context.Context) int {
	count, err := oq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (oq *OutcomeQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, oq.ctx, "Exist")
	switch _, err := oq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (oq *OutcomeQuery) ExistX(ctx context.Context) bool {
	exist, err := oq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the OutcomeQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (oq *OutcomeQuery) Clone() *OutcomeQuery {
	if oq == nil {
		return nil
	}
	return &OutcomeQuery{
		config:            oq.config,
		ctx:               oq.ctx.Clone(),
		order:             append([]OrderFunc{}, oq.order...),
		inters:            append([]Interceptor{}, oq.inters...),
		predicates:        append([]predicate.Outcome{}, oq.predicates...),
		withProbabilities: oq.withProbabilities.Clone(),
		// clone intermediate query.
		sql:  oq.sql.Clone(),
		path: oq.path,
	}
}

// WithProbabilities tells the query-builder to eager-load the nodes that are connected to
// the "probabilities" edge. The optional arguments are used to configure the query builder of the edge.
func (oq *OutcomeQuery) WithProbabilities(opts ...func(*ProbabilityQuery)) *OutcomeQuery {
	query := (&ProbabilityClient{config: oq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	oq.withProbabilities = query
	return oq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Text string `json:"text,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Outcome.Query().
//		GroupBy(outcome.FieldText).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (oq *OutcomeQuery) GroupBy(field string, fields ...string) *OutcomeGroupBy {
	oq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &OutcomeGroupBy{build: oq}
	grbuild.flds = &oq.ctx.Fields
	grbuild.label = outcome.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Text string `json:"text,omitempty"`
//	}
//
//	client.Outcome.Query().
//		Select(outcome.FieldText).
//		Scan(ctx, &v)
func (oq *OutcomeQuery) Select(fields ...string) *OutcomeSelect {
	oq.ctx.Fields = append(oq.ctx.Fields, fields...)
	sbuild := &OutcomeSelect{OutcomeQuery: oq}
	sbuild.label = outcome.Label
	sbuild.flds, sbuild.scan = &oq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a OutcomeSelect configured with the given aggregations.
func (oq *OutcomeQuery) Aggregate(fns ...AggregateFunc) *OutcomeSelect {
	return oq.Select().Aggregate(fns...)
}

func (oq *OutcomeQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range oq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, oq); err != nil {
				return err
			}
		}
	}
	for _, f := range oq.ctx.Fields {
		if !outcome.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if oq.path != nil {
		prev, err := oq.path(ctx)
		if err != nil {
			return err
		}
		oq.sql = prev
	}
	return nil
}

func (oq *OutcomeQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Outcome, error) {
	var (
		nodes       = []*Outcome{}
		_spec       = oq.querySpec()
		loadedTypes = [1]bool{
			oq.withProbabilities != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Outcome).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Outcome{config: oq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(oq.modifiers) > 0 {
		_spec.Modifiers = oq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, oq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := oq.withProbabilities; query != nil {
		if err := oq.loadProbabilities(ctx, query, nodes,
			func(n *Outcome) { n.Edges.Probabilities = []*Probability{} },
			func(n *Outcome, e *Probability) { n.Edges.Probabilities = append(n.Edges.Probabilities, e) }); err != nil {
			return nil, err
		}
	}
	for name, query := range oq.withNamedProbabilities {
		if err := oq.loadProbabilities(ctx, query, nodes,
			func(n *Outcome) { n.appendNamedProbabilities(name) },
			func(n *Outcome, e *Probability) { n.appendNamedProbabilities(name, e) }); err != nil {
			return nil, err
		}
	}
	for i := range oq.loadTotal {
		if err := oq.loadTotal[i](ctx, nodes); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (oq *OutcomeQuery) loadProbabilities(ctx context.Context, query *ProbabilityQuery, nodes []*Outcome, init func(*Outcome), assign func(*Outcome, *Probability)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Outcome)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.Probability(func(s *sql.Selector) {
		s.Where(sql.InValues(outcome.ProbabilitiesColumn, fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.outcome_probabilities
		if fk == nil {
			return fmt.Errorf(`foreign-key "outcome_probabilities" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "outcome_probabilities" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (oq *OutcomeQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := oq.querySpec()
	if len(oq.modifiers) > 0 {
		_spec.Modifiers = oq.modifiers
	}
	_spec.Node.Columns = oq.ctx.Fields
	if len(oq.ctx.Fields) > 0 {
		_spec.Unique = oq.ctx.Unique != nil && *oq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, oq.driver, _spec)
}

func (oq *OutcomeQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   outcome.Table,
			Columns: outcome.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: outcome.FieldID,
			},
		},
		From:   oq.sql,
		Unique: true,
	}
	if unique := oq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := oq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, outcome.FieldID)
		for i := range fields {
			if fields[i] != outcome.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := oq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := oq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := oq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := oq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (oq *OutcomeQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(oq.driver.Dialect())
	t1 := builder.Table(outcome.Table)
	columns := oq.ctx.Fields
	if len(columns) == 0 {
		columns = outcome.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if oq.sql != nil {
		selector = oq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if oq.ctx.Unique != nil && *oq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range oq.predicates {
		p(selector)
	}
	for _, p := range oq.order {
		p(selector)
	}
	if offset := oq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := oq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// WithNamedProbabilities tells the query-builder to eager-load the nodes that are connected to the "probabilities"
// edge with the given name. The optional arguments are used to configure the query builder of the edge.
func (oq *OutcomeQuery) WithNamedProbabilities(name string, opts ...func(*ProbabilityQuery)) *OutcomeQuery {
	query := (&ProbabilityClient{config: oq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	if oq.withNamedProbabilities == nil {
		oq.withNamedProbabilities = make(map[string]*ProbabilityQuery)
	}
	oq.withNamedProbabilities[name] = query
	return oq
}

// OutcomeGroupBy is the group-by builder for Outcome entities.
type OutcomeGroupBy struct {
	selector
	build *OutcomeQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (ogb *OutcomeGroupBy) Aggregate(fns ...AggregateFunc) *OutcomeGroupBy {
	ogb.fns = append(ogb.fns, fns...)
	return ogb
}

// Scan applies the selector query and scans the result into the given value.
func (ogb *OutcomeGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ogb.build.ctx, "GroupBy")
	if err := ogb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*OutcomeQuery, *OutcomeGroupBy](ctx, ogb.build, ogb, ogb.build.inters, v)
}

func (ogb *OutcomeGroupBy) sqlScan(ctx context.Context, root *OutcomeQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(ogb.fns))
	for _, fn := range ogb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*ogb.flds)+len(ogb.fns))
		for _, f := range *ogb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*ogb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ogb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// OutcomeSelect is the builder for selecting fields of Outcome entities.
type OutcomeSelect struct {
	*OutcomeQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (os *OutcomeSelect) Aggregate(fns ...AggregateFunc) *OutcomeSelect {
	os.fns = append(os.fns, fns...)
	return os
}

// Scan applies the selector query and scans the result into the given value.
func (os *OutcomeSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, os.ctx, "Select")
	if err := os.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*OutcomeQuery, *OutcomeSelect](ctx, os.OutcomeQuery, os, os.inters, v)
}

func (os *OutcomeSelect) sqlScan(ctx context.Context, root *OutcomeQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(os.fns))
	for _, fn := range os.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*os.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := os.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
