// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/cleodora-forecasting/cleodora/cleosrv/ent/estimate"
	"github.com/cleodora-forecasting/cleodora/cleosrv/ent/outcome"
	"github.com/cleodora-forecasting/cleodora/cleosrv/ent/predicate"
	"github.com/cleodora-forecasting/cleodora/cleosrv/ent/probability"
)

// ProbabilityQuery is the builder for querying Probability entities.
type ProbabilityQuery struct {
	config
	ctx          *QueryContext
	order        []OrderFunc
	inters       []Interceptor
	predicates   []predicate.Probability
	withEstimate *EstimateQuery
	withOutcome  *OutcomeQuery
	withFKs      bool
	modifiers    []func(*sql.Selector)
	loadTotal    []func(context.Context, []*Probability) error
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ProbabilityQuery builder.
func (pq *ProbabilityQuery) Where(ps ...predicate.Probability) *ProbabilityQuery {
	pq.predicates = append(pq.predicates, ps...)
	return pq
}

// Limit the number of records to be returned by this query.
func (pq *ProbabilityQuery) Limit(limit int) *ProbabilityQuery {
	pq.ctx.Limit = &limit
	return pq
}

// Offset to start from.
func (pq *ProbabilityQuery) Offset(offset int) *ProbabilityQuery {
	pq.ctx.Offset = &offset
	return pq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (pq *ProbabilityQuery) Unique(unique bool) *ProbabilityQuery {
	pq.ctx.Unique = &unique
	return pq
}

// Order specifies how the records should be ordered.
func (pq *ProbabilityQuery) Order(o ...OrderFunc) *ProbabilityQuery {
	pq.order = append(pq.order, o...)
	return pq
}

// QueryEstimate chains the current query on the "estimate" edge.
func (pq *ProbabilityQuery) QueryEstimate() *EstimateQuery {
	query := (&EstimateClient{config: pq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := pq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := pq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(probability.Table, probability.FieldID, selector),
			sqlgraph.To(estimate.Table, estimate.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, probability.EstimateTable, probability.EstimateColumn),
		)
		fromU = sqlgraph.SetNeighbors(pq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryOutcome chains the current query on the "outcome" edge.
func (pq *ProbabilityQuery) QueryOutcome() *OutcomeQuery {
	query := (&OutcomeClient{config: pq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := pq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := pq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(probability.Table, probability.FieldID, selector),
			sqlgraph.To(outcome.Table, outcome.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, probability.OutcomeTable, probability.OutcomeColumn),
		)
		fromU = sqlgraph.SetNeighbors(pq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Probability entity from the query.
// Returns a *NotFoundError when no Probability was found.
func (pq *ProbabilityQuery) First(ctx context.Context) (*Probability, error) {
	nodes, err := pq.Limit(1).All(setContextOp(ctx, pq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{probability.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (pq *ProbabilityQuery) FirstX(ctx context.Context) *Probability {
	node, err := pq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Probability ID from the query.
// Returns a *NotFoundError when no Probability ID was found.
func (pq *ProbabilityQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = pq.Limit(1).IDs(setContextOp(ctx, pq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{probability.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (pq *ProbabilityQuery) FirstIDX(ctx context.Context) int {
	id, err := pq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Probability entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Probability entity is found.
// Returns a *NotFoundError when no Probability entities are found.
func (pq *ProbabilityQuery) Only(ctx context.Context) (*Probability, error) {
	nodes, err := pq.Limit(2).All(setContextOp(ctx, pq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{probability.Label}
	default:
		return nil, &NotSingularError{probability.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (pq *ProbabilityQuery) OnlyX(ctx context.Context) *Probability {
	node, err := pq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Probability ID in the query.
// Returns a *NotSingularError when more than one Probability ID is found.
// Returns a *NotFoundError when no entities are found.
func (pq *ProbabilityQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = pq.Limit(2).IDs(setContextOp(ctx, pq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{probability.Label}
	default:
		err = &NotSingularError{probability.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (pq *ProbabilityQuery) OnlyIDX(ctx context.Context) int {
	id, err := pq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Probabilities.
func (pq *ProbabilityQuery) All(ctx context.Context) ([]*Probability, error) {
	ctx = setContextOp(ctx, pq.ctx, "All")
	if err := pq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Probability, *ProbabilityQuery]()
	return withInterceptors[[]*Probability](ctx, pq, qr, pq.inters)
}

// AllX is like All, but panics if an error occurs.
func (pq *ProbabilityQuery) AllX(ctx context.Context) []*Probability {
	nodes, err := pq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Probability IDs.
func (pq *ProbabilityQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	ctx = setContextOp(ctx, pq.ctx, "IDs")
	if err := pq.Select(probability.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (pq *ProbabilityQuery) IDsX(ctx context.Context) []int {
	ids, err := pq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (pq *ProbabilityQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, pq.ctx, "Count")
	if err := pq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, pq, querierCount[*ProbabilityQuery](), pq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (pq *ProbabilityQuery) CountX(ctx context.Context) int {
	count, err := pq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (pq *ProbabilityQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, pq.ctx, "Exist")
	switch _, err := pq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (pq *ProbabilityQuery) ExistX(ctx context.Context) bool {
	exist, err := pq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ProbabilityQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (pq *ProbabilityQuery) Clone() *ProbabilityQuery {
	if pq == nil {
		return nil
	}
	return &ProbabilityQuery{
		config:       pq.config,
		ctx:          pq.ctx.Clone(),
		order:        append([]OrderFunc{}, pq.order...),
		inters:       append([]Interceptor{}, pq.inters...),
		predicates:   append([]predicate.Probability{}, pq.predicates...),
		withEstimate: pq.withEstimate.Clone(),
		withOutcome:  pq.withOutcome.Clone(),
		// clone intermediate query.
		sql:  pq.sql.Clone(),
		path: pq.path,
	}
}

// WithEstimate tells the query-builder to eager-load the nodes that are connected to
// the "estimate" edge. The optional arguments are used to configure the query builder of the edge.
func (pq *ProbabilityQuery) WithEstimate(opts ...func(*EstimateQuery)) *ProbabilityQuery {
	query := (&EstimateClient{config: pq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	pq.withEstimate = query
	return pq
}

// WithOutcome tells the query-builder to eager-load the nodes that are connected to
// the "outcome" edge. The optional arguments are used to configure the query builder of the edge.
func (pq *ProbabilityQuery) WithOutcome(opts ...func(*OutcomeQuery)) *ProbabilityQuery {
	query := (&OutcomeClient{config: pq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	pq.withOutcome = query
	return pq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Value int `json:"value,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Probability.Query().
//		GroupBy(probability.FieldValue).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (pq *ProbabilityQuery) GroupBy(field string, fields ...string) *ProbabilityGroupBy {
	pq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ProbabilityGroupBy{build: pq}
	grbuild.flds = &pq.ctx.Fields
	grbuild.label = probability.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Value int `json:"value,omitempty"`
//	}
//
//	client.Probability.Query().
//		Select(probability.FieldValue).
//		Scan(ctx, &v)
func (pq *ProbabilityQuery) Select(fields ...string) *ProbabilitySelect {
	pq.ctx.Fields = append(pq.ctx.Fields, fields...)
	sbuild := &ProbabilitySelect{ProbabilityQuery: pq}
	sbuild.label = probability.Label
	sbuild.flds, sbuild.scan = &pq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ProbabilitySelect configured with the given aggregations.
func (pq *ProbabilityQuery) Aggregate(fns ...AggregateFunc) *ProbabilitySelect {
	return pq.Select().Aggregate(fns...)
}

func (pq *ProbabilityQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range pq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, pq); err != nil {
				return err
			}
		}
	}
	for _, f := range pq.ctx.Fields {
		if !probability.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if pq.path != nil {
		prev, err := pq.path(ctx)
		if err != nil {
			return err
		}
		pq.sql = prev
	}
	return nil
}

func (pq *ProbabilityQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Probability, error) {
	var (
		nodes       = []*Probability{}
		withFKs     = pq.withFKs
		_spec       = pq.querySpec()
		loadedTypes = [2]bool{
			pq.withEstimate != nil,
			pq.withOutcome != nil,
		}
	)
	if pq.withEstimate != nil || pq.withOutcome != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, probability.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Probability).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Probability{config: pq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(pq.modifiers) > 0 {
		_spec.Modifiers = pq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, pq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := pq.withEstimate; query != nil {
		if err := pq.loadEstimate(ctx, query, nodes, nil,
			func(n *Probability, e *Estimate) { n.Edges.Estimate = e }); err != nil {
			return nil, err
		}
	}
	if query := pq.withOutcome; query != nil {
		if err := pq.loadOutcome(ctx, query, nodes, nil,
			func(n *Probability, e *Outcome) { n.Edges.Outcome = e }); err != nil {
			return nil, err
		}
	}
	for i := range pq.loadTotal {
		if err := pq.loadTotal[i](ctx, nodes); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (pq *ProbabilityQuery) loadEstimate(ctx context.Context, query *EstimateQuery, nodes []*Probability, init func(*Probability), assign func(*Probability, *Estimate)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*Probability)
	for i := range nodes {
		if nodes[i].estimate_probabilities == nil {
			continue
		}
		fk := *nodes[i].estimate_probabilities
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(estimate.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "estimate_probabilities" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (pq *ProbabilityQuery) loadOutcome(ctx context.Context, query *OutcomeQuery, nodes []*Probability, init func(*Probability), assign func(*Probability, *Outcome)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*Probability)
	for i := range nodes {
		if nodes[i].outcome_probabilities == nil {
			continue
		}
		fk := *nodes[i].outcome_probabilities
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(outcome.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "outcome_probabilities" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (pq *ProbabilityQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := pq.querySpec()
	if len(pq.modifiers) > 0 {
		_spec.Modifiers = pq.modifiers
	}
	_spec.Node.Columns = pq.ctx.Fields
	if len(pq.ctx.Fields) > 0 {
		_spec.Unique = pq.ctx.Unique != nil && *pq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, pq.driver, _spec)
}

func (pq *ProbabilityQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   probability.Table,
			Columns: probability.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: probability.FieldID,
			},
		},
		From:   pq.sql,
		Unique: true,
	}
	if unique := pq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := pq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, probability.FieldID)
		for i := range fields {
			if fields[i] != probability.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := pq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := pq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := pq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := pq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (pq *ProbabilityQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(pq.driver.Dialect())
	t1 := builder.Table(probability.Table)
	columns := pq.ctx.Fields
	if len(columns) == 0 {
		columns = probability.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if pq.sql != nil {
		selector = pq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if pq.ctx.Unique != nil && *pq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range pq.predicates {
		p(selector)
	}
	for _, p := range pq.order {
		p(selector)
	}
	if offset := pq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := pq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ProbabilityGroupBy is the group-by builder for Probability entities.
type ProbabilityGroupBy struct {
	selector
	build *ProbabilityQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (pgb *ProbabilityGroupBy) Aggregate(fns ...AggregateFunc) *ProbabilityGroupBy {
	pgb.fns = append(pgb.fns, fns...)
	return pgb
}

// Scan applies the selector query and scans the result into the given value.
func (pgb *ProbabilityGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, pgb.build.ctx, "GroupBy")
	if err := pgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ProbabilityQuery, *ProbabilityGroupBy](ctx, pgb.build, pgb, pgb.build.inters, v)
}

func (pgb *ProbabilityGroupBy) sqlScan(ctx context.Context, root *ProbabilityQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(pgb.fns))
	for _, fn := range pgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*pgb.flds)+len(pgb.fns))
		for _, f := range *pgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*pgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := pgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ProbabilitySelect is the builder for selecting fields of Probability entities.
type ProbabilitySelect struct {
	*ProbabilityQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ps *ProbabilitySelect) Aggregate(fns ...AggregateFunc) *ProbabilitySelect {
	ps.fns = append(ps.fns, fns...)
	return ps
}

// Scan applies the selector query and scans the result into the given value.
func (ps *ProbabilitySelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ps.ctx, "Select")
	if err := ps.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ProbabilityQuery, *ProbabilitySelect](ctx, ps.ProbabilityQuery, ps, ps.inters, v)
}

func (ps *ProbabilitySelect) sqlScan(ctx context.Context, root *ProbabilityQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ps.fns))
	for _, fn := range ps.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ps.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ps.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
