name: Build Windows

on:
  workflow_dispatch:

jobs:
  build-windows:
    name: Build on Windows
    runs-on: windows-latest
    defaults:
      run:
        shell: bash

    steps:
      - uses: msys2/setup-msys2@v2
        with:
          update: true
          install: mingw-w64-x86_64-toolchain mingw-w64-x86_64-sqlite3
          msystem: MINGW64
          path-type: inherit

      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
          cache: true

      - name: Build
        run: go build -o cleosrv.exe github.com/cleodora-forecasting/cleodora/cleosrv
        shell: msys2 {0}

      - name: List directory content
        run: ls

      - name: Display version
        run: ./cleosrv.exe version

      - name: 'Save cleosrv.exe'
        uses: actions/upload-artifact@v3
        with:
          name: cleosrv.exe
          path: cleosrv.exe
          retention-days: 2
