name: Frontend Tests
on:
  push:
    tags:
      - v*
    branches:
      - main
    paths:
      - .github/workflows/**
      - frontend/**
  pull_request:
    paths:
      - .github/workflows/**
      - frontend/**

jobs:
  build:
    name: Build and Test
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        working-directory: frontend
        run: npm ci

      # Just to ensure it also works, not needed for tests
      - name: Build
        working-directory: frontend
        run: npm run build

      - name: Test
        working-directory: frontend
        run: npm test
