name: Frontend Lint
on:
  push:
    tags:
      - v*
    branches:
      - main
    paths:
      - .github/workflows/**
      - frontend/**
  pull_request:
    paths:
      - .github/workflows/**
      - frontend/**

jobs:
  build:
    name: lint
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        working-directory: frontend
        run: npm ci

      - name: Lint
        working-directory: frontend
        run: npx eslint src
