name: frontend lint
on:
  push:
    tags:
      - v*
    branches:
      - main
    paths:
      - .github/workflows/**
      - frontend/**
  pull_request:
    paths:
      - .github/workflows/**
      - frontend/**

jobs:
  build:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Lint
        working-directory: frontend
        run: npm run lint
