name: Go Lint
on:
  push:
    tags:
      - v*
    branches:
      - main
    paths-ignore:
      - README.md
      - design/**
      - docs/**
      - e2e_tests/**
      - frontend/**
      - website/**
  pull_request:
    paths-ignore:
      - README.md
      - design/**
      - docs/**
      - e2e_tests/**
      - frontend/**
      - website/**

permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  # pull-requests: read
jobs:

  goreleaser-check:
    name: goreleaser-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: Run check
        shell: bash
        run: go run github.com/goreleaser/goreleaser check

  golangci:
    timeout-minutes: 5
    strategy:
      matrix:
        build_tag: [default, production, mage] # Note that 'default' is not a tag we actually use
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      # Required, otherwise some linters fail because there is nothing to embed
      - name: Create cleosrv/cleosrv/frontend_build/unused.html
        if: ${{ matrix.build_tag == 'production' }}
        shell: bash
        run: |
          mkdir -p cleosrv/cleosrv/frontend_build/
          touch cleosrv/cleosrv/frontend_build/unused.html

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
          version: latest

          # Optional: working directory, useful for monorepos
          # working-directory: somedir

          # Optional: golangci-lint command line arguments.
          args: --build-tags ${{ matrix.build_tag }}

          # Optional: show only new issues if it's a pull request. The default value is `false`.
          # only-new-issues: true

          # Optional: if set to true then the all caching functionality will be complete disabled,
          #           takes precedence over all other caching options.
          # skip-cache: true

          # Optional: if set to true then the action don't cache or restore ~/go/pkg.
          # skip-pkg-cache: true

          # Optional: if set to true then the action don't cache or restore ~/.cache/go-build.
          # skip-build-cache: true
