name: Go tests

on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
          cache: true

      - name: Test
        run: go test -v ./...
